# -*- coding: utf-8 -*-
"""resizer_tool

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B0RJ-VzOLbWvYXULUY1cGWQzgtqfg8hr
"""

!pip install pillow

import os
from PIL import Image

def resize_single_image(input_file, output_file, new_size=(800, 600), quality=85, format='PNG'):
    try:
        if not os.path.exists(input_file):
            print(f"Input file not found: {input_file}")
            return False

        img = Image.open(input_file)

        img_resized = img.resize(new_size, Image.LANCZOS)

        output_dir = os.path.dirname(output_file)
        if output_dir and not os.path.exists(output_dir):
            os.makedirs(output_dir)

        img_resized.save(output_file, format=format, quality=quality)

        print(f"Successfully resized image: {input_file} -> {output_file}")
        return True

    except Exception as e:
        print(f"Error processing image: {str(e)}")
        return False

input_image = "/content/sample_image.png"
output_image = "/content/resized_image.png"

resize_single_image(
    input_image,
    output_image,
    new_size=(800, 600),
    quality=85,
    format='PNG'
)